### ISSUE TITLE
display issue carbon emissions

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#103]
We currently have a flex display with carbon emissions. However, these are not total carbon emissions, but only carbon emissions from fossil fuels (see data information). So the label for the display is wrong 

![image](https://user-images.githubusercontent.com/18350553/138324000-c681a677-1a95-44fb-a5d7-e7be27d90e4e.png)

![image](https://user-images.githubusercontent.com/18350553/138324291-f25408fb-0275-4815-b957-dcbead34ae06.png)

for new release, suggest to update flex display with
- change display name to carbon emissions from fossil fuels (using the carann variable)
- add display with carbon emissions from deforestation (using the carforoth variable)
- add display with total carbon emissions (sum of carann+carforoth)
- add history and forecast for all three of the above

**Comment by PardeeCenterIFs** [comment]
I was able to do the first and second requests, but not the 3rd and 4th because CARFOROTH is a global variable, not specific to countries, so we can't add it, except for the World in a fixed display, also because it's a global variable it doesn't have a historic analog, since those are only country specific.
