### ISSUE TITLE
Education Intake: Solomon Islands

### ISSUE THREAD

**Issue by A-pirzadeh** [PardeeCenterDU/IFs-Issues-Tracking#109]
Description: Irregular behavior for the Solomon Islands when looking at education intake levels. Intake data is probably poor because enrollment and survival are at high rates.
Date Found: 10/13/2021
IFs Version: 7.77
Found by: Resource Team

![image](https://user-images.githubusercontent.com/83729959/138516648-689b1e1a-892a-4922-95d7-a6c89d3a386e.png)

**Comment by PardeeCenterIFs** [comment]
Mohammod says:

It is a data issue, as Audrey wrote in the initial issue entry. The flex display is using a single series. It should use the sum of three series, SeriesEDPRINIRENTRNTotal, SeriesEDPRINIRENTRNP1Total, SeriesEDPRINIRENTRNM1Total, for entrants of-age, over-age by a year and underage by a year. Same thing, needs to be done for boys and girls. I am not sure who created the flex display. I can fix it if you would like me to.

**Comment by mtirfan66** [comment]
The data tables were not merged as suggested in the comment above. Please let me know if I need to do it.
Once the data tables are merged, the flex display also need to change. 
Thank you.

**Comment by PardeeCenterIFs** [comment]
I'm sorry, I understood from your comment on Jun 2022 that the suggestion was to change the variable list to use a Sum, not to create a new table, besides if you're going to change the variable list anyway, why bother creating a new table. But anyway, please do fix it at your earliest convenience, and in the way that you think it's more appropriate.

**Comment by mtirfan66** [comment]
I am guessing PardeeCenterIFs is Jose. Jose, you are right, my earlier suggestions was to add three tables. I have two questions on  that, a. I have to create an altogether new display to add these three tables as historical analog with formula, right, as the current one uses historic analog column from IFsVar,? b. I see a problem with the addition. The sum should be used only when all three tables have values for the same country-year. Is there an option in the IFs formula tool to set this rule?
Thanks in advance.

**Comment by PardeeCenterIFs** [comment]
Yes, I'm (José) using the PardeeCenterIFs account, but I also use my personal account solox1, so if you want to tag me, better to use solox1. 
a. Historical Analogs are not usually tied to a Variable List, they're tied to a variable, so no need to create a new Variable List.
b. I think this is the same question as in the e-mail thread, the default behaviour is that A + B + C will be Null if any of the elements in the equation is Null (Agregation is a different thing, better try it with individual countries).

**Comment by PardeeCenterIFs** [comment]
I just checked this issue again, and I do see we're adding up the 3 tables, say for Solomon Islands in 2018:
SeriesEDPRINIRENTRNTotal is 9.23197
SeriesEDPRINIRENTRNM1Total is 0.06444
SeriesEDPRINIRENTRNP1Total is 27.75538
Which adds up to 37.05 which is what the display is now showing, but the Forecast value in the base year is still much higher, around 80.

**Comment by mtirfan66** [comment]
In the older ed model (no grades), net intake rate would be reconciled with other net flow rates   in the pre-proc, prioritizing enrollment and survival rates over intake rate. So, the jump will stay between history and forecast for Solomon Islands and, possibly, other countries.  

In the  new ed model, grade data is used, and reconciliation is not needed. So, the history and forecast should not show a jump. That's what it was doing in VB6 (I checked 7.92 code). The code routine for adding up the three tables (for of-age, 1-yr underage and 1-yr overage entrances:  SeriesEDPRINIRENTRNTotal, SeriesEDPRINIRENTRNM1 and  SeriesEDPRINIRENTRNP1) was not translated properly to .net. The same table (SeriesEDPRINIRENTRNM1) was being read for both underage and overage entrance. This needed fix in .net code in vb and C#. Code changes was also needed so the 2018 data is accepted for the 2019 (or, a potential 2020) base. All code changes are marked with 'mti 2024/05/07

The code change has affected NIR, significantly, only for 4 countries (SI, Liberia, Niger, I am blanking out on the other). This is only for new ed model. Generally, the results look okay so far.
  
Here is the Solomon Islands plot with and without the fix for the new ed model:

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/7fe4d3b6-0d90-4143-b23d-94a944a39bd5)
