### ISSUE TITLE
Group Exchange Issue

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#115]
Version 7.78 (and at least 7.77, perhaps earlier)

When I import groups via an exchange file I receive an "Item not found" error. The groups appear in Flex or Self Managed, but they cannot be used (produce empty graphs with a "group not found" error). Attached is the transmission file I have been using (though I have confirmed this on others as well).

[VarListTransmission_UNICEF.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/7419585/VarListTransmission_UNICEF.zip)

![image](https://user-images.githubusercontent.com/12075041/138914593-ef599ae2-c579-49e1-aa1c-4498885d433a.png)

![image](https://user-images.githubusercontent.com/12075041/138914349-66fc3583-6478-4a17-a234-5c3234e0ce06.png)

![image](https://user-images.githubusercontent.com/12075041/138914459-1b5e2228-809d-4895-b47a-51dc40eef7fb.png)

**Comment by PardeeCenterIFs** [comment]
This issue was also reported by Jonathan, but I had not realized the second part, trying to use the Groups, producina a Group not found, I guess that goes away if you restart the model, that's why I had originally assign a priortity 3 to this issue, but anyway, I have now fixed it, and I can recreate version 7.78 with this fix, or if not it will be included in version 7.79.

https://github.com/PardeeCenterDU/IFs-Issues-Tracking/issues/116
