### ISSUE TITLE
Check if regression needs update: GDP/Capita (PPP 2011) Versus Computer Owning Households(MOSTRECENT) Log

### ISSUE THREAD

**Issue by PardeeCenterIFs** [PardeeCenterDU/IFs-Issues-Tracking#139]
INFRASTR.bas
IFsInfra (in 2 places, first year and all but first):

                'mti 2015/05/06 - start
                'Temporary replcament with a simpe rregression of % of households with computers on GDP PCP (Logistic function)
                TbName$ = "GDP/Capita (PPP 2011) Versus Computer Owning Households(MOSTRECENT) Log"  'function for earlier years yet to be estimated
                'mti 2015/05/06 – end

                'Temporary replcament with a simpe rregression of % of households with computers on GDP PCP (Logistic function)
                'mti 2015/05/06 - start
                TbName$ = "GDP/Capita (PPP 2011) Versus Computer Owning Households(MOSTRECENT) Log"  'function for earlier years yet to be estimated
                'mti 2015/05/06 – end

**Comment by mtirfan66** [comment]
The original regression done by Dale Rothman included electricity use and regulation quality alongside GDP PCP.
Later the definition of the computer ownership variable needed to be changed from "computers per 100 individuals" to "share of households with at least one computer," to reflect data availability from ITU.
The exact reasons are not clear, but perhaps for reasons like lack of fit or multi-collinearity, the previous IVs were dropped. The new regression shows a good fit of 78%.

a. At this point, the data is quite old. Even after a 2019 ITU update, the most recent year with good data coverage is 2013. Computer ownership is increasing fast. So, I would wait for new data before I try new relationship/s.
b. I used the IFs tool of best 100 fit with current data. Most of the top performers are income and/or poverty. That gives one other reason to keep it as is for now. 5.50 poverty gives a much better fit (82%), compared to 1.90 poverty (69%), probably because no 1.90 poverty for higher income countries. Our 5.50 poverty forecast is new and not as well tested as 1.90 poverty though.  We can consider using poverty, once we get more recent data.  For now, let's hang on to what we have.

![image](https://user-images.githubusercontent.com/53452620/149413974-63ba7759-b0b8-43d7-8047-253d96ebcbca.png)
