### ISSUE TITLE
Updating preprocessor undernourishment series

### ISSUE THREAD

**Issue by wverhagen** [PardeeCenterDU/IFs-Issues-Tracking#165]
For the USAID food security project, we want to update the undernourishment pre-processor series.

Specifically we want to fill holes in the pre-processor series and we want to replace the current calculation of clpccv with the data on clpccv.

the full procedure is discussed over the email, and attached as a word document.
[Updating malnourished population routine in data preprocessor yx_wv.docx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/8186475/Updating.malnourished.population.routine.in.data.preprocessor.yx_wv.docx)

The timeline for this project is:
- update the preprocessor by March 17
- Dave and Willem will review
- Final update done by April 1

**Comment by PardeeCenterIFs** [comment]
Adding e-mail conversation:

Not sure. Dave, you might have a better sense here as well.

POPMEDAGE seems like a fairly straightforward to calculate. The more consistency we can get between data filling holes and the projections, the better I think.

Willem

From: Jose Solorzano Arevalo 
Sent: Tuesday, March 8, 2022 11:27 PM
To: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Willem,

We can’t use POPMEDAGE in the preprocessor, it’s only computed in the regular years of the run, so this estimation can’t be used in the preprocessor unless we do a significant effort to compute that one also in the preprocessor, I don’t think it’s worth it.

Call XYTABL("CLPCMDER (Linear) versus POPMEDAGE (X^2)", POPMEDAGE(R%), Est)

José

From: Jose Solorzano Arevalo 
Sent: Tuesday, March 8, 2022 4:08 PM
To: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Willem,

I also think that we should fill holes for CLPC first, so that we can use it to fill holes for MALNPOP if necessary, and that way we don’t need to find a GDPPCP relationship, and just use the existing one.

José

From: Jose Solorzano Arevalo 
Sent: Tuesday, March 8, 2022 1:08 PM
To: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Willem,

For the moment I’m only using the base year for this complicated logic, finding a different year would be very difficult.

On the document you say:

“Fill in wholes for malnourished population using existing GDP per capita function. If now 3 out of 4 data series exist, calculate the missing series based on the calculation of malnourished population.” 

But we’re not currently using a GD per capita function, we’re using calories per capita function, so I assume that means we need to find a new GDPPCP function, could you please confirm? The current code actually tries to create a longitudinal regression to get an estimate:

CMALNPOPP(ICount%) = getYearOrFitLineOnXYrs(MalnPopPTbl, BaseYear, 10)

Shouldn’t we try this first?

José

From: Jose Solorzano Arevalo 
Sent: Monday, March 7, 2022 10:55 AM
To: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Hi Willem,

2. Can you clarify, can we use MostRecent or not? If we use it, we can’t warrantee we’re using only 1 year. I assume we can’t, for example for CLPCCV.

We will have to switch from this:

CCLPCCV(ICount%) = getYearOrMstRct(CLPCCVTbl, BaseYear)

To:

CCLPCCV(ICount%) = CLPCCVTbl.Fields(BaseYear)

José

From: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)> 
Sent: Monday, March 7, 2022 4:47 AM
To: Jose Solorzano Arevalo <[jsolorza@du.edu](mailto:jsolorza@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Hi José,

1.	You are right
2.	Correct as well. Initially we try to take only data from 1 year, and then do whole filling based on the number of series available

Would the code then need a rule, take data from year with most data points available. I.e. if clpc, mder and cv is available for 2016 but malnpopp is available for 2017, we would want to fill holes for 2016 and use that as an initial estimate. Correct? Or would this complicate/create errors in the procedure.

Thanks,
Willem

From: Jose Solorzano Arevalo 
Sent: Friday, March 4, 2022 9:29 PM
To: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Willem,

2 questions on the following steps:

-	Do a check whether most recent actually results in all data coming from the same year.
-	Do not yet fill in any holes in the data


1.	We don’t always use most recent data, so this check seems irrelevant, we might instead check what year we use to fill in our initialization.
2.	Do not fill holes? But I can take data from different years? I see that for CLPC if the base year doesn’t exist we don’t use Most Recent, but some other linear estimation, that shouldn’t be the case anymore, right? So for now we take the base year or nothing for CLPC at this step.

            CCLPC(ICount%, 1) = getYearOrFitLineOnXYrs(CLPCCropTbl, BaseYear, 10)
            CCLPC(ICount%, 2) = getYearOrFitLineOnXYrs(CLPCMeatTbl, BaseYear, 10)

José

From: Jose Solorzano Arevalo 
Sent: Friday, March 4, 2022 2:01 PM
To: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Sounds good.

José

From: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)> 
Sent: Friday, March 4, 2022 1:56 PM
To: Jose Solorzano Arevalo <[jsolorza@du.edu](mailto:jsolorza@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Hi Jose,

You are right. Lets not touch the CLPC logic here for fish. That’s a lot of data series and probably too much to fully integrate.
If possible the other meat and crop (that’s only 2 right) would be nice though.

Willem

From: Jose Solorzano Arevalo 
Sent: Friday, March 4, 2022 7:48 PM
To: Willem Verhagen <[Willem.Verhagen@du.edu](mailto:Willem.Verhagen@du.edu)>; David Bohl <[David.Bohl@du.edu](mailto:David.Bohl@du.edu)>; Yutang Xiong <[Yutang.Xiong@du.edu](mailto:Yutang.Xiong@du.edu)>
Subject: RE: data preprocessor update for undernourishment series

Hi Willem,

I had not realized that you want to include CLPC in this logic, do you really want me to keep track of the year used for each of the 11 types of fish?
This fish logic is going to be super complicated to change, I might have been wrong on my estimation of time needed if that is the case.

José

**Comment by PardeeCenterIFs** [comment]
This is now implemented and it will be included in version 7.83
