### ISSUE TITLE
Arms Exports and Imports Forecast Years Values Too Low

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#172]
I have seen some odd behavior in arms exports and imports in my model. The initial year is initialized correctly, but later years are displaying values much lower than expected. After reviewing the code, it seems to me that the issue may be similar to #156. Two graphs are included below. The first shows the expected behavior from a 7.82 install and the second shows what I am seeing.

Expected Behavior:
![image](https://user-images.githubusercontent.com/7695597/158846299-ce0a8d56-ea1d-43ae-8ae0-b15e4bf049d9.png)

 
Observed Behavior:
![image](https://user-images.githubusercontent.com/7695597/158846370-d62cbf58-6272-4bf6-bd03-eea255067a88.png)

 
This is coming from a version that has Jose’s fixes and my changes to influence. These are limited to the Influence subroutine besides the declaration of a couple variables. I attempted to recreate the problem in a 7.82 install and did not see the same behavior.

IFs Version: 7.82 VB.Net dev version with Influence changes

**Comment by caleb-petry** [comment]
In _ifsEcoDyadic1AllButFirst_, replace:

> New Single() {XDYAD(j, II, 2), GDS(II, Mil), GDS(j, Mil), contig1, DistanceBilat(II, j)}, ValEst,

With:

> New Single() {XDYAD(j, II, 2), sgds(II, Mil), sgds(j, Mil), contig1, DistanceBilat(II, j)}, ValEst,

**Comment by PardeeCenterIFs** [comment]
Hi Caleb,

I'm impresed you fond this one. If the bilateral was on in the base case, this would be what we call a run to run, namely because we're trying to use GDS before it's being computed in the logic, that's why you need to use sgds, which saves the values from the previous year.

The reason you see the "Expected" values in the first version, is because that's actually vb6, which has the same problem, but in vb6 GDS before it gets computed has the base case value, in .NET it has a 0, so vb6 is also wrong, but not noticeable, so I have made these changes both in .NET and vb6, thanks for finding this issue. The fix will be included in version 7.83.
