### ISSUE TITLE
Monadic Arms Trade

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#182]
From Email Thread: FBIC in IFs: Adding Monadic Arms

An outline of the proposed addition is...
![image](https://user-images.githubusercontent.com/7695597/161291100-67f43ae5-24a4-4a43-8690-df19834016e9.png)

**Comment by PardeeCenterIFs** [comment]
We wish to add monadic arms forecasts to IFs and use them to constrain the dyadic forecasts. Attached are two provisional series in an .mdb, they are SeriesArmsImports%GDP and SeriesArmsExports%GDP. Below, I have outlined a general idea of what we want to add. If you want to discuss it, feel free to reach out to me and we can find a time.
1.	Initializing Monadic Arms Trade
a.	Initialize both imports and exports as a percent of GDP from data
b.	Use these to create initial values in currency form
c.	Constrain imports using military expenditures. For now,  let's make it so that imports cannot exceed 50% of military expenditures. We may wish to parameterize this as something like armsimmaxpctmilex.
d.	Reconcile the currency values privileging imports using something like "Exportsfinal = globalSumOfImports / globalSumOfExportsinital"
e.	Save final reconciled values 
2.	Forecasting Monadic Arms Trade
a.	In later years, the forecast will be simple and driven solely by GDP for now. Put otherwise, we will keep the initial percent of GDP constant for now.
b.	Include parameters along the lines of these examples: armsexadd, armexsm, armsimadd, and armsimm 
c.	Constrain by military expenditures
d.	Reconcile the currency values and save them for the display
3.	Ties to Dyadic Arms Trade
a.	Use the existing arms exports model to generate initial dyadic forecasts
b.	Apply the existing process for dyadic trade (or a similar function) to reconcile these initial forecasts with monadic arms exports and imports

**Comment by PardeeCenterIFs** [comment]
This implementation has been completed and it will be included in version 7.84
