### ISSUE TITLE
.NET Install Error

### ISSUE THREAD

**Issue by A-pirzadeh** [PardeeCenterDU/IFs-Issues-Tracking#186]
.NET Install Error
4/7/2022
.NETv7.83
Audrey Pirzadeh

When installing the .NETv7.83 version, I originally chose the file path were VB6 versions are installed and received the "localhost refused to connect" error when trying to open the .NETv7.83 version. I have since not been given the option to distinguish the file path for installation and it automatically goes to the VB6 file path (C:\Users\Public\.NET v7.83). I tried deleting the .NET version and redownloading it from the server, but I still do not have the option to choose the file path.

![image](https://user-images.githubusercontent.com/83729959/162279522-9af3a2e4-e903-4a6d-80a0-c8b0f0b247ae.png)

**Comment by PardeeCenterIFs** [comment]
Where you able to uninstall?

**Comment by A-pirzadeh** [comment]
I had to re-install to be able to uninstall (because it was previously just deleted), and now the .NET version is functioning. I still did not receive the option to choose the file path and it installed where VB6 versions are, but it works now. Wondering if I should uninstall and reinstall just to test if that would correct the file path.

**Comment by PardeeCenterIFs** [comment]
I just tried uninstalling, and installing again, and it is actually asking me for a location:

![image](https://user-images.githubusercontent.com/33665510/163276754-4c86b08d-7cf7-4936-a67d-5ac603541b53.png)

So I can't reproduce this issue, maybe the registry got damaged in your machine by deleting instead of uninstalling, not sure.
