### ISSUE TITLE
.NET maxUrlLength error

### ISSUE THREAD

**Issue by markmeziere** [PardeeCenterDU/IFs-Issues-Tracking#187]
Description: In flex displays I had selected 4 variables (MFP social, physical, human, knowledge). Horizon 2100. Group WB Low Income. Choose to display a line graph and received the maxUrlLength error (see screenshot).

Date found: 4/7/22

Version: IFs .NET 7.83

Found by: Mark

Type of error: Server Error

Replication: Flex displays. Select 4 variables (MFP social, physical, human, knowledge). Horizon 2100. Group WB low income. Display a line graph.

MFP (social, phys, human knowledge) - WB Low income - line graph - 2100 base

![image](https://user-images.githubusercontent.com/84362289/162284201-436894ef-94d9-43fd-b079-4de8c8f4c6eb.png)

**Comment by PardeeCenterIFs** [comment]
Can you show a screen shot of the selected displays so that we have their full names, I can't find one called MFP Social, I see MFPSC with components (Formulation in IFs) which has like 4 components, but I don't think that's what you meant. I don't see an MFP that allows you to select the dimension, as Social, Physical, etc.

**Comment by markmeziere** [comment]
Absolutely. My apologies for not writing out the full names.

![image](https://user-images.githubusercontent.com/84362289/162642109-8f72760b-f214-480f-be04-db365cfb4bb1.png)

**Comment by PardeeCenterIFs** [comment]
Thank you Mark, I was able to reproduce the issue and will assign it to Jaime.

**Comment by PardeeCenterIFs** [comment]
Jaime has fixed this issue, and the fix will be included in version 7.85.
