### ISSUE TITLE
Error on loading scenario in .NET

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#195]
Short Description: Error on loading scenario
Description: I attempted to load the attached scenario, but encountered an error (screenshot below)
Date found: 04/26/2022
IFs Version: IFs 7.83 .NET; on local VM (Windows 11)
Reproduced, including after an IIS restart.
Not reproducible in IFs 7.82 Guinea Bissau (VB6 install; with new education model switch)

[GBc03_combined.txt](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/8566125/GBc03_combined.txt)
![image](https://user-images.githubusercontent.com/12075041/165372588-d67249f9-0575-4a72-9831-a967c70a13f5.png)
![image](https://user-images.githubusercontent.com/12075041/165372832-3016b470-1553-4e5d-a53e-302028a60f58.png)

**Comment by PardeeCenterIFs** [comment]
I couldn't reproduce this issue, I was able to load the sce file with no problems. This could be one of those were IIS restarted midway and we lost our session variables, but I'm surprised that you can reproduce it. Is it possible you had started a run that was using a scenario, and that's why we get that message that working.sce is being used by another process.
