### ISSUE TITLE
Unable to Use Groups in History and Forecast Bilateral Display

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#207]
I am unable to use groups in using history and forecast for the core FBIC series. When I attempt to do so for Influence with the China-Asia ASEAN dyad using a table, the following error message is returned:

![image](https://user-images.githubusercontent.com/7695597/170550152-49943653-759a-470f-8e2b-4c5cf039a2e9.png)

IFs Version: 7.84 .Net Development with Code/Data Updates

**Comment by caleb-petry** [comment]
Decomposed groups appear to work fine. It might be an issue with aggregating historical series?

**Comment by PardeeCenterIFs** [comment]
It was an issue with the aggregation calculation in the .NET version, the structure of the table changed for .NET, now using SQLite for the forecast part, and the logic was still replicating the vb6 logic instead of using the new structure.

I have fix this issue and it should be included in version 7.85.
