### ISSUE TITLE
Issue with PovAgeSexGeneric when running IFs in Portuguese

### ISSUE THREAD

**Issue by Coryv221** [PardeeCenterDU/IFs-Issues-Tracking#209]
For Ifs in Portuguese, we have the data being processed so that whether the user uses "," or "." for their values. For some reason, the "PovAgeSexGeneric" series does not convert correctly and causes us to get mismatched type errors. We do have a temporary solution in place, but in the long term, need it tested on IFs in Portuguese and working without the fix, to make sure we don't limit scalability to future localizations.

The code is in the Economy.bas module, and under the tag 'cdv 2022/03/22 (vb6)

The issue does not occur in .NET, but value format localization works automatically in both, in theory.

**Comment by PardeeCenterIFs** [comment]
I just checked the table, and field 0-4, 5-9 and 10-14 are of type short text, they should be number as other age ranges are.

Cory, when you get to this, give it a try, simply changing the data type, and see if that fixes the issues on translation so that we can remove the temp fix. Once you have confirmed it I will make the change permanent in the consolidated version.

**Comment by Coryv221** [comment]
Just adding a note for myself:

We should have updated the data table this week, and I will be testing if changing the data types fixed the issue

**Comment by mtirfan66** [comment]
This should have been closed by Cory. I am closing it.
