### ISSUE TITLE
IFsDataImport.db gets reset when new table is being added

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#263]
I was doing a IFs data importation training and my IFsDataImport.db file already has some tables in it. Then I proceeded add one more table through IFs. The new table was added succesfully but other tables got eliminated. I've never encoutered this issue before. My guess is that the IFsDataImport.db file was opened by SQLiteStudio during the importation process and somehow IFs decided to create a new IFsDataImport.db file to overite the current one? Or there was a commit conflict in the SQLite?

This issue happened at the time stamp 30:43

https://mediaspace.du.edu/media/Workshop-+IFs+Data+Import/1_2ejgxt0e?st=85380

**Comment by quciet** [comment]
In the recording, there was also another issue. When I was importing an existing table in IFs, the AGG RULE and Decimal Points were preloaded from the current DataDict table and could not be changed. Can we still load them from the current DataDict table but also allow users to make changes, especially for the decimal points. 

This happened at the time stamp 26:00

Thanks you so much!

**Comment by PardeeCenterIFs** [comment]
On the first issue, it wasn't happening because SQLite Studio was open, but instead it was resetting the ifsDataImport.db file, always that you click on Import for a "Long" format series. I have fixed this now.

On the second issue, I have now enable those combos to change Aggregation Rule and Decimal Places for existing variables.

Both fixes will be included in version 8.18.
