### ISSUE TITLE
Issue with historical data visualization

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#264]
When I go to Longitudinal Display and try to plot PopMigration (or PopMigrationyears or PopMigrationyearsWDI) I get an error that says there is no data.  But there is data in IFsHistSeries.  Something is wrong.

**Comment by PardeeCenterIFs** [comment]
PopMigration doesn't work because the names of the fields are not individual years.
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/33665510/2645a20e-440f-4b1d-b68f-ddccddec1f5e)
PopMigrationYears works fine:
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/33665510/13194623-4ba4-4925-a430-721ec1e873ab)
Same PopMigrationYearsWDI:
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/33665510/8827c5bd-392f-49fe-b40c-aeadf33c4904)

**Comment by quciet** [comment]
Hi both,

I'm not familiar with these tables, but somehow I think PopMigration and PopMigrationYears were intentionally made that way. One use the range and other one use the starting year. 
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/31d21944-8169-4ab7-88a1-4f327ffc2f8c)

What do you suggest we do?

**Comment by jonathandmoyer** [comment]
Hmm... When I was looking at this yesterday I wasn't seeing history and
forecast for Flex display issues related to migration and I wonder if my
use of the dyadic migration model didn't somehow mess that up....

I see that our longitudinal series is UNPDForecastNetMigration which is
probably fine--I guess it would be nice not to show variables in Data
Analysis that you can't actually see but I'm not sure how complex that is
-----
  Jonathan D Moyer, PhD
  Assistant Professor
  Director
  Frederick S. Pardee Center for International Futures
  Josef Korbel School of International Studies
  University of Denver

**Comment by PardeeCenterIFs** [comment]
Much easier to simply change the column names so that the table can be seen, which, seems to me, is what we did with the PopMigrationYears table.

**Comment by quciet** [comment]
I've manually fixed this for the next data delivery (IFs8.19)
