### ISSUE TITLE
% issue & panel data importation issue

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#270]
Seems the ghost of % is still there to be taken down. I'm using version 8.18 with this file [Validation_PIP.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14454560/Validation_PIP.xlsx). Importing sheet SeriesIncBelow2D15c%PIP gives me following issue.
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/9746d097-479f-4c94-a69b-595033fe787d)

Another issue happens when importing sheet SeriesIncMedPIP. Year columns are eliminated after import.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/5a821937-a3d2-49cd-b2d8-f5cd7444a2b1)

**Comment by PardeeCenterIFs** [comment]
The error seems to happen when trying to drop an existing table in ifsDataImport.db, so it seems to me that a workaround could be to delete manually the table. Anyway, I have now fixed the "%" for the Drop statement, and it will be included in version 8.19.

Regarding the years not loading, that's because this is not in our regular "Long" format. The format is supposed to have Countries in the first column, and years in the second, but in this case FIPS_CODE is in the 2nd column and the year in the third, so that causes the problem, fix the file and it works.

**Comment by quciet** [comment]
> The error seems to happen when trying to drop an existing table in ifsDataImport.db, so it seems to me that a workaround could be to delete manually the table. Anyway, I have now fixed the "%" for the Drop statement, and it will be included in version 8.19.
> 
> Regarding the years not loading, that's because this is not in our regular "Long" format. The format is supposed to have Countries in the first column, and years in the second, but in this case FIPS_CODE is in the 2nd column and the year in the third, so that causes the problem, fix the file and it works.

I think the Data Import interface provides an option for users to help IFs to identify the columns of country & year, is that not working?

**Comment by PardeeCenterIFs** [comment]
I have added code now to allow years to be in a different column, other than the first. This fix will be included in version 8.19.
