### ISSUE TITLE
Computations Issue (two of them)

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#275]
Go to Self Managed, choose Decomposed Groups, Computations, a/b, resor(oil) world, pop world, you only get zimbabwe.

Do the same but with Groups (instead of decomposed) you get the world--go to a table and choose "transpose and decompose" and you get the same value for all countries.

**Comment by PardeeCenterIFs** [comment]
On the first issue, that option should be blocked, too difficult to implement, so I have disabled it. You can alternatively create a formula and then apply a G-List in Self Managed by clicking on the recently created formula.

On the second issue, I was able to fix the problem, which was introduce when we started trying handling formulas that do something like resor(oil)(CountryA)/resolr(oil)(World) back in May of 2017. Anyway the fix for this will be included in version 8.20.
