### ISSUE TITLE
remove some old energy preprocessros?

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#278]
These preprocessors have not been updated for a while and we cannot find them from the original data source (WRI) anymore, should we remove them from the model? I do believe the information from these tables are already covered by data from the IEA. We purchase data from IEA every two years and they cover energy production and consumption across different energy types.
 
SeriesEnConPhoto,	Energy consumption, photovoltaic solar	
SeriesEnConWind, Energy consumption, wind	
SeriesEnConElec, Electricity consumption total in BBOE	
SeriesEnProdGeoTherm, Energy production, geothermal	
SeriesEnProdTideWave, Energy production, tide, wave, and water	
SeriesEnProdSolar, Energy production, solar	

Thanks!

**Comment by BarryBHughes** [comment]
Yutang,

The data on these renewable energy sources should be best in IEA rather than WRI, so as long we have series updates every 2 years from IEA I think we are ok!  But production and consumption patterns for them are changing rapidly, so we will want to update with new releases as soon as we can.

Barry

Barry B. Hughes, Distinguished University Professor
Senior Scientist and Mentor
Frederick S. Pardee Center for International Futures
Josef Korbel School of International Studies
University of Denver, Denver, Colorado 80208 USA
Mobile: +1 303 847 1828
Connect with the Pardee Center and IFs Online<https://korbel.du.edu/pardee>
Connect with my web page<https://korbel.du.edu/pardee/about/history/founder>

From: Yutang ***@***.***>
Sent: Thursday, March 14, 2024 2:23 PM
To: PardeeCenterDU/IFs-Issues-Tracking ***@***.***>
Cc: Barry Hughes ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [PardeeCenterDU/IFs-Issues-Tracking] remove some old energy preprocessros? (Issue #278)

[External Email From]: ***@***.******@***.***>


These preprocessors have not been updated for a while and we cannot find them from the original data source (WRI) anymore, should we remove them from the model? I do believe the information from these tables are already covered by data from the IEA. We purchase data from IEA every two years and they cover energy production and consumption across different energy types.

SeriesEnConPhoto, Energy consumption, photovoltaic solar
SeriesEnConWind, Energy consumption, wind
SeriesEnConElec, Electricity consumption total in BBOE
SeriesEnProdGeoTherm, Energy production, geothermal
SeriesEnProdTideWave, Energy production, tide, wave, and water
SeriesEnProdSolar, Energy production, solar

Thanks!

**Comment by quciet** [comment]
@BarryBHughes Appreciate this quick response! The subscription to IEA is funded by the DIPLO team and we will make sure they get updated within the month of their release. There is also a related question to the data we pulled from IEA (https://github.com/PardeeCenterDU/IFs-Issues-Tracking/issues/227). Basically, IEA energy types have more than what are currently covered by IFs, we probably need to restructure the initialization during the next update.

Hi @solox1, based on Barry's comment, I think it is safe to delete those 6 old energy preprocessors from the model code and IFsHistSeries, what do you think? Or at least remove them from the model code to avoid marking them as preprocessors in the DataDict table so that RAs won't need to go through them again next time.

**Comment by BarryBHughes** [comment]
Quick comment on the removal of WRI series as drivers in the preprocessor  --I suspect they were there before we had access to IEA, but we’d want to make sure that they aren’t written in as sources to fill holes in IEA data (e.g. if WRI had estimaes of Palestine and IEA did not).


From: Yutang ***@***.***>
Sent: Thursday, March 14, 2024 2:44 PM
To: PardeeCenterDU/IFs-Issues-Tracking ***@***.***>
Cc: Barry Hughes ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [PardeeCenterDU/IFs-Issues-Tracking] remove some old energy preprocessros? (Issue #278)

[External Email From]: ***@***.******@***.***>


@BarryBHughes<https://urldefense.com/v3/__https:/github.com/BarryBHughes__;!!NCZxaNi9jForCP_SxBKJCA!WGjod8CdyahmlIaYYXz1wIX0-uyhsVgo1q_XAK633LoLOo3-3ZIKyuJiw6LFPS82sPAYYkxsfIpGfGdwkrJrXts$> Appreciate this quick response! The subscription to IEA is funded by the DIPLO team and we will make sure they get updated within the month of their release. There is also a related question to the data we pulled from IEA (#227<https://urldefense.com/v3/__https:/github.com/PardeeCenterDU/IFs-Issues-Tracking/issues/227__;!!NCZxaNi9jForCP_SxBKJCA!WGjod8CdyahmlIaYYXz1wIX0-uyhsVgo1q_XAK633LoLOo3-3ZIKyuJiw6LFPS82sPAYYkxsfIpGfGdwr029CRc$>). Basically, IEA energy types have more than what are currently covered by IFs, we probably need to restructure the initialization during the next update.

Hi @solox1<https://urldefense.com/v3/__https:/github.com/solox1__;!!NCZxaNi9jForCP_SxBKJCA!WGjod8CdyahmlIaYYXz1wIX0-uyhsVgo1q_XAK633LoLOo3-3ZIKyuJiw6LFPS82sPAYYkxsfIpGfGdwUJleD9A$>, based on Barry's comment, I think it is safe to delete those 6 old energy preprocessors from the model code and IFsHistSeries, what do you think? Or at least remove them from the model code to avoid marking them as preprocessors in the DataDict table so that RAs won't need to go through them again next time.

**Comment by PardeeCenterIFs** [comment]
I just checked and we're using them to fill holes after we have checked there's no IEA data, but in all cases where IEA is NULL the values for WRI are 0s from 1999 or earlier, so I think it's better to remove them and let the model put a small seed instead.

**Comment by quciet** [comment]
> I just checked and we're using them to fill holes after we have checked there's no IEA data, but in all cases where IEA is NULL the values for WRI are 0s from 1999 or earlier, so I think it's better to remove them and let the model put a small seed instead.

Sounds perfect! I can make the change on my end (deleting those tables) once you make the change in the code. Let me know!

**Comment by PardeeCenterIFs** [comment]
I have now removed these 6 tables, they will not be used in version 8.26 and forward.
