### ISSUE TITLE
SSP5 doesn't run past 2150 because of population issues

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#283]
[SSP5 - Copy.sce.txt](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14619810/SSP5.-.Copy.sce.txt)

**Comment by caleb-petry** [comment]
@jonathandmoyer, could you confirm whether or not (1) the version is 8.18 and (2) whether or not it has the extended migration series?

Will add more later, but...
- Fatal Error Cause (WHEN SAVING AT END OF RUN): Population in UAE goes to zero circa 2136 causing a fatal error in the next year through GDPPC and AG prices process (Causing NaNs to start appearing in other places as well).

- Without the extended migration table in my dev 8.18 (initially an error when returning to this issue), I am able to get it to run by adding the line "CUSTOM,migrateoutm,United Arab Emirates,1:6,0@85,0:500]"; Since these tables include information about population in the ratio, I could see the extended version exacerbating the issue. @caleb-petry, check how 'null' values are handled from 2100 to 2200.
- I am also able to get it to run by removing only the 'wmigrm' line without the extended tables.

- Per the email thread, it seems that 8.19 shifts push the crossover later.

**Comment by PardeeCenterIFs** [comment]
This issue has been fixed aftere implementing 3 changes:

1. Adding a tighter limit to the number of deaths per 5-year age category, The limit use to be the entire population, so that it wouldn't go negative, but now we force it to leave at least 100 people in each 5-year category.
2. Adding a limit to the number of outward migration, so that it wouldn't wipe out the entire population of a given age, the limit is now 100.
3. Recomputing Infrastructure Public Budge after adjusment, because it was producing ratios over 1, and potentially growing ratios that became infinity, or NaN.

These fixes will be included in version 8.20.
