### ISSUE TITLE
IFs8.21 error when rebuilding and running the model

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#298]
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/ae9be695-20b7-4664-8c20-edfe75268512)
This is the error message. And I've attached the log file too. This is a fresh IFs8.21. All we did was rebuilding the base and running the model to year 2100.

[Uploading 2024-04-24.log…]()

**Comment by PardeeCenterIFs** [comment]
There have been several attempts to fix this issue:

1. In the Trip to Ethiopia in January of 2024 I was able to fix it by replacing the compiled GUI with non-compiled GUI code in the target machine.
2. We later found out that this issue was exacerbated by using Multi-threading, which became an option that you can turn off, which is now off by default.
3. The 2nd option seemed to work for most cases, but then we started getting this error again, but it seems to have been fixed when we moved to using ifs.exe, instead of dotnet.exe ifs.dll in version 8.22.
