### ISSUE TITLE
Displaying multiple bi-variate functions together

### ISSUE THREAD

**Issue by mtirfan66** [PardeeCenterDU/IFs-Issues-Tracking#308]
VB6 allowed selecting multiple functions together. This was very useful for comparing functions drawn with same or related data (e.g., all per student cost functions shown in the plot below drawn in VB6).
Is it possible to have this back.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/53452620/f7df2bae-8b2f-4a37-863c-95414bb1d71a)

**Comment by PardeeCenterIFs** [comment]
If you go to Main Menu, Data Analysis, Show Computed Functions, and then select the subset of functions you want to display, then click on the menu Graph, Draw, you should have them, although there seemed to be a problem when trying to select 4 graphs, this will be fixed in version 8.27, and showing 3 or less already worked in earlier versions.
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/33665510/f0640ea6-83a2-409d-8476-90e062be3583)
