### ISSUE TITLE
Working.run.db getting reset by IFsBase.run.db when Working.sce is present

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#310]
This issue was discovered during the BIGPOPA project and will affect the Python set up used for the project. More details can be found here, https://github.com/PardeeCenterDU/BIGPOPA/issues/1

**Comment by PardeeCenterIFs** [comment]
Ok, I have now moved it out of ForecastAll, since in most cases this is handled by the GUI, no need to copy base to working again. The only case we need this is for the big batch logic, so I moved it to the Launch procedure in Vanilla.vb that handles the big batch run.

This change will be included in version 8.26 and forward.
