### ISSUE TITLE
hlcomaddmort 

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#311]
I choose hlcomaddmort for 80+ and make it high.  I run it to 2040 for World.  I go to J-Curve and look at the base and working file for 2030 for world for total mortality and I get an error.

**Comment by PardeeCenterIFs** [comment]
There were 2 issues here:

1. Groupings were not working since we moved to all sqlite files.
2. Changing scenarios was not updating.

Both items have been fixed and they will be included in version 8.25.

Furthermore you need to use hlcomaddmort in combination with hlcomaddprev, only changing the former will not produce any change.
