### ISSUE TITLE
Scenario Analysis Bug--maybe I trapped it?

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#318]
i've had an issue when making scenarios that goes like this:  I make a scenario in the tree, I then save it, I then want to adjust the parameters to make a scenario that's "worse" by using customization.  When I do that, I enter the adjustment in customization and it looks 1000% OK.  Then, I when I hit continue to go to scenario analysis, it shows a weird starting value in the first year.  See the image below.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/85649722/312c69c4-678f-4c04-a876-e40847f6ce39)
[UNContinuation.sce.txt](https://github.com/user-attachments/files/15919298/UNContinuation.sce.txt)

Here's what I did and what you should be able to replicate (ojala) with the following instructions:
Take the attached sce file and load it in quick scenario. 
Click on the QE ratio multiplier which should go from 1 to 2 over 15 years or so.  Click on it and hit customize.  For value, choose 4.  Interpolate for 15 years.  Change for 150 years.  Exit to tree.  You should see the image above.

If this is caught, it would make building scenarios much easier.

**Comment by PardeeCenterIFs** [comment]
This problem was related to using customizations for parameters with more than 1 dimension, qem has 2 dimensions, and OtherRenew is 6, and that 6 was being written at the begining of the values incorrectly.
The fix for this will be included version 8.27, the work around is to the customizations manually directly on the sce file.
