### ISSUE TITLE
Child Stunting 

### ISSUE THREAD

**Issue by A-pirzadeh** [PardeeCenterDU/IFs-Issues-Tracking#48]
Child Stunting HLSTUNTCHL
Date Found: 5/3/2021
IFs Version 7.66
Found by: Audrey Pirzadeh
![HLSTUNTCHL](https://user-images.githubusercontent.com/83729959/117204336-6cb9de80-adad-11eb-95cd-c4a93132e5b9.jpg)
Description: some countries act irregular for the HLSTUNTCHL variable

**Comment by PardeeCenterIFs** [comment]
This big jump in stunting is produced by the new formulation:

Child Stunting vs Child Malnutrition and Adult Female Sec. Completion

The values for Child Stunting were negative in this function for Tonga before 2043, and thus using a seed of 1E-06, in 2043 they’re small but positive, 0.0345731974, thus producing a big jump.
We
The drivers in 2042 were:

? MALNCHP(R%)
1.85844278
? EDSECPER(R%, 2)
63.84758

In 2043:

? MALNCHP(R%)
1.85766578
? EDSECPER(R%, 2)
63.441803

Stunt Work goes up until 2047-2048, by the way goes crazy above 100, and it’s supposed to be a rate.

**Comment by PardeeCenterIFs** [comment]
We were already using a multiplicative shift, which are helpful to keep the proportions of changes, but they are problematic when having a change in sign, like this one.

So basically we have a multiplicate shift factor, which must be huge, since the initial value is very small (1E-6), and the growth once it becomes negative is huge too: 0.03/1E-6 = 30k, so we’re probably hitting the limit on stunting.

**Comment by PardeeCenterIFs** [comment]
Mohammod has now implemented a solution where if the analycial function returns a negative value we will use an additive shift factor instead of a multiplicative one. This should be fixed in version 7.67, but more changes were also implemented around stunting, regarding incorporation of SAM.
