### ISSUE TITLE
 MALNPOPP goes above 100 percent

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#50]
**Short Description:** In a scenario which increases CLPCCV (using _clpccvm_), MALNPOPP goes above 100 percent for several countries, and increases dramatically for several others.

**Date found:** 05/10/21

**IFs Version:** 7.66 VB6 Development

**Found by:** David Bohl

**Error Type:** Model dynamics

**Description:** In a scenario which increases CLPCCV (_clpccvm_ interpolated from 1 in 2017 to 1.2 by 2020), MALNPOPP goes above 100 percent for several countries (Bahrain, Equatorial Guinea, Micronesia), and increases dramatically for several others (Bhutan, China, Ireland, Puerto Rico, Qatar, Singapore, USA). While going above 100 percent should be impossible, it is not clear if the rapid increase is a bug, or simply a function of very low CLCPCV. 

**Steps to Replicate:**
1. Run the following scenarios: [cv00Base.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/6472831/cv00Base.zip)
2. Look at MALNPOPP for the countries listed above

**Screenshots:**
![image](https://user-images.githubusercontent.com/12075041/118135655-46a9c500-b3d1-11eb-8463-820d3abe65ba.png)

**Comment by PardeeCenterIFs** [comment]
The problem seems to be the multiplicative shift, which is too sensitive to big changes in the analytical function.
In the particular case of Equatorial Guinea when we create a scenario that increases CLPCCV from 0.115 to 0.12, that produces a change in the analytical function from 7.660371E-04 to 1.897807E-03, which is almost a 150% growth, so that triggers the big change in MALNPOP from 28 to 69 in just one year.

The solution could be to use additive shift factors instead, but I see we have tried that in the past, I see it's commented out, so that might show behaviour that is too flat, or incovenient in some other way.

                MALNPOPP(R%) = pct * ConvergeOverTime(malnpoppi(R%), 1, 86)
                'MALNPOPP(R%) = AMAX(pct + malnpoppi(R%), 0)

**Comment by PardeeCenterIFs** [comment]
Swithcing back to an additive shift factor, but this time with convergence to 0 over 30 year seems to improve this scenario.

![MALNPOP with Additive shift](https://user-images.githubusercontent.com/33665510/118326592-6836a980-b4c2-11eb-86a1-37d95db31263.jpg)
