### ISSUE TITLE
Scenario with malnmm yields unexpected behavior for MALNCHP

### ISSUE THREAD

**Issue by dkbohl** [PardeeCenterDU/IFs-Issues-Tracking#51]
**Short Description:** Scenario with _malnmm_ yields unexpected behavior for MALNCHP.

**Date found:** 05/10/21

**IFs Version:** 7.66 VB6 Development

**Found by:** David Bohl

**Error Type:** Model dynamics

**Description:** In a scenario which increases MALNCHP by 20 percent over 5 years (using _malnmm_), MALNCHP increases far beyond the expected 20 percent for several countries (Burundi, Chad, Djibouti, Eritrea, India, Moldova, Niger, Sudan, Timor-Leste, Tonga, Ukraine, Yemen), and even falls for others (South Sudan and Madagascar).

**Steps to Replicate:**
1. Run the following scenarios (_st0Base_ is the same as _cv00Base_): [st2malnm.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/6472879/st2malnm.zip)
2. Look at MALNCHP for the countries listed above

**Screenshots:**
![image](https://user-images.githubusercontent.com/12075041/118137024-ba000680-b3d2-11eb-9aba-587258a558d2.png)

**Comment by PardeeCenterIFs** [comment]
The problem is this piece of code for countries like Yemen:

                MaxChg = 5
                malncomp = AMAX(malncomp, SMalnChP(R%) - MaxChg)
                malncomp = Amin(malncomp, SMalnChP(R%) + MaxChg)
                MALNCHP(R%) = malncomp

the analitical function is dropping the value of malncomp, but the AMAX statement keeps it at least 5% below the previous value, thus making malncomp to increase.

I'm thinking moving up the code that saves SMalnChP, so that it's before the multiplier, solves the problem. Currently SMalnChp is only used here, so it should be fine.

![MALNCHP_YEMEN](https://user-images.githubusercontent.com/33665510/118196763-d029b900-b40a-11eb-903d-735c63d5de1a.jpg)
