### ISSUE TITLE
Cross sectional is broken in 7.73

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#84]
Go to Cross Sectional, TFR Most Recent, GDP2011PCPPP Most Recent, Plot, model dies.  

Could someone please follow up with me and tell me how this bug was introduced?  Thank you

**Comment by PardeeCenterIFs** [comment]
This issue was reported by Barry on Sep 1st via e-mail, and it was fixed that day, the fix is included in version 7.74.

Barry:

Inside cross-sectional please pick LaborParRate15PlusFemale% - most recent and then LaborParRate15PlusMale% - most recent.   When in 7.73 I try to do a plot I get a subscript out of range.  Possibly because both series go to 2020?

José: 

Unfortunately this is not an error specific to those series, but to all series, so in version 7.73 you can’t use Cross-Sectional, the reason is that the Group Update had a new numeration id, and there’s some adjustment needed to handle it. The new numeration is generated automatically I think when we import the group, as we recently did for the standardization of Group names recently.
